package cli

import "github.com/spf13/cobra"

// RegisterRoutes attaches every command group defined in the cli package
// to the provided root command. Each module exposes its own root command
// (e.g. NetworkCmd) which aggregates all micro routes such as ~start and
// ~stop. Calling RegisterRoutes(root) makes all commands available from
// the main binary so they can be invoked like `synnergy ~network ~start`.
func RegisterRoutes(root *cobra.Command) {
	// modules with exported command variables
	root.AddCommand(
		NetworkCmd,
		ConsensusCmd,
		AdaptiveCmd,
		TokensCmd,
		TokenMgmtCmd,
		CoinCmd,
		ContractsCmd,
		VMCmd,
		TransactionsCmd,
		PrivateTxCmd,
		ReversalCmd,
		TxDistributionCmd(),
		WalletCmd,
		ExecutionCmd,
		DeFiCmd,
		RegulatoryCmd,
		FeedbackCmd,
		AccountCmd,
		IDWalletCmd,
		OffWalletCmd,
		RecoveryCmd,
		WalletMgmtCmd,
		AICmd,
		AITrainingCmd,
		AIMgmtCmd,
		AIInferenceCmd,
		AMMCmd,
		PoolsCmd,
		PollsCmd,
		BioCmd,
		AuthCmd,
		AuthorityApplyCmd,
		CharityCmd,
		TimelockCmd,
		DAOCmd,
		LoanCmd,
		StakeCmd,
		LoanApplyCmd,
		EventsCmd,
		ComplianceCmd,
		AuditCmd,
		ComplianceMgmtCmd,
		CrossChainCmd,
		ImmutabilityCmd,
		DataCmd,
		DistributionCmd,
		OracleMgmtCmd,
		DataOpsCmd,
		HACmd,
		CompressionCmd,
		AnomalyCmd,
		ResourceCmd,
		PlasmaCmd,
		ChannelRoute,
		ZTChannelCmd,
		StorageRoute,
		ResourceCmd,
		DAOAccessCmd,
		sensorCmd,
		RealEstateCmd,
		EscrowRoute,
		MarketplaceCmd,
		HealthcareCmd,
		UtilityRoute,
		EnergyCmd,
		InitRepCmd,
		FinalizationCmd,
		StakingCmd,
		BinaryTreeCmd,
		StakingCmd,
		QuadraticCmd,
		quorumCmd,
		SwarmCmd,
		WorkflowCmd,
		EcommerceCmd,
		EmploymentCmd,
		DevnetCmd,
		TestnetCmd,
		FaucetCmd,
		SupplyCmd,
		TangibleCmd,
		WarehouseCmd,
		GamingCmd,
	)

	// modules that expose constructors
	root.AddCommand(
		NewFaultToleranceCommand(),
		NewFailoverCommand(),
		NewGovernanceCommand(),
		NewTokenVoteCommand(),
		NewGovernanceManagementCommand(),
		NewRepGovCommand(),
		NewGreenCommand(),
		NewLedgerCommand(),
		NewReplicationCommand(),
		NewSyncCommand(),
		NewRollupCommand(),
		NewSecurityCommand(),
		NewShardingCommand(),
		NewSidechainCommand(),
		NewHealthCommand(),
	)
}
