name: Build

on:
  push:
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
      - name: Build
        run: |
          cd synnergy-network
          go mod tidy
          go build ./...
      - name: Test
        run: |
          cd synnergy-network
          go test ./...

  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - synnergy-network/GUI/token-creation-tool/server
          - synnergy-network/GUI/dao-explorer/backend
          - synnergy-network/GUI/smart-contract-marketplace
          - synnergy-network/GUI/storage-marketplace/backend
          - synnergy-network/GUI/nft_marketplace/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
      - name: Install
        run: |
          cd ${{ matrix.package }}
          npm install
      - name: Test
        run: |
          cd ${{ matrix.package }}
          npm run test --if-present
